import type { HeritageNode } from "./types";

export const HERITAGE_NODES: HeritageNode[] = [
  {
    id: "kim-bong-carpentry",
    name: "Làng Mộc Kim Bồng",
    nameEn: "Kim Bong Carpentry Village",
    craftCategory: "carpentry",
    coordinates: [108.3274, 15.8866],
    coverImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80",
    tier: 2,
    artisanName: "Ông Nguyễn Văn Tiến",
    artisanAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80",
    knowledgeSummary:
      "Làng mộc Kim Bồng là làng nghề truyền thống hơn 400 năm tuổi tại Hội An, chuyên chạm khắc gỗ tinh xảo phục vụ kiến trúc đình chùa và nội thất cung đình nhà Nguyễn. Kỹ thuật đục đẽo tay truyền từ đời này sang đời khác.",
    knowledgeSummaryEn:
      "Kim Bong carpentry village is a traditional craft village over 400 years old in Hoi An, specializing in intricate wood carving for communal house architecture and Nguyen dynasty interiors. Hand-carving techniques are passed down through generations.",
    materials: ["Gỗ mít", "Đục chạm", "Bào tay", "Sơn mài"],
    videoUrl: undefined,
    npcScript: [
      {
        order: 1,
        question: "Ông học nghề từ khi nào?",
        answer:
          "Tôi học nghề từ năm 12 tuổi, theo cha học đục chạm. Hồi đó mỗi ngày đục đến tay chai cứng mà vẫn chưa được cha khen — ông bảo phải 5 năm mới gọi là 'biết nghề'.",
      },
      {
        order: 2,
        question: "Bí quyết chạm khắc đẹp là gì?",
        answer:
          "Quan trọng nhất là 'đọc thớ gỗ' — mỗi loại gỗ có hướng thớ riêng. Đục xuôi thớ thì nhẹ tay, đục ngược thớ sẽ vỡ. Gỗ mít Kim Bồng đặc biệt — không mối mọt, giữ nét chạm hàng trăm năm.",
      },
      {
        order: 3,
        question: "Nghề mộc Kim Bồng có điều gì đặc biệt nhất?",
        answer:
          "Chúng tôi không chỉ làm đồ gỗ — chúng tôi làm 'ký ức'. Mỗi mảnh chạm khắc là câu chuyện của một gia đình, một ngôi làng. Khi bạn chạm vào tác phẩm Kim Bồng, bạn đang chạm vào 400 năm lịch sử Hội An.",
      },
    ],
    photoChallenge: {
      prompt: "Chụp ảnh một người thợ đang đục chạm gỗ",
      promptEn: "Photograph a craftsman carving wood",
      referenceImages: [
        "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400&q=70",
        "https://images.unsplash.com/photo-1561361398-832e764d7ac4?w=400&q=70",
      ],
    },
    items: [
      {
        id: "kbcv-001",
        name: "Đục chạm trổ Kim Bồng",
        nameEn: "Kim Bong Carving Chisel",
        craftCategory: "carpentry",
        sourceNodeId: "kim-bong-carpentry",
        sourceNodeName: "Làng Mộc Kim Bồng",
        artisanName: "Ông Nguyễn Văn Tiến",
        image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&q=80",
        rarity: "Common",
        description: "Mẫu đục chạm trổ bằng thép già, cán gỗ mít. Biểu tượng nghề thủ công Kim Bồng.",
        descriptionEn: "Traditional carving chisel with aged steel blade and jackwood handle. Iconic symbol of Kim Bong craft.",
        dropRate: 0.6,
      },
      {
        id: "kbcv-002",
        name: "Hoa văn rồng chầu",
        nameEn: "Dragon Motif Relief Panel",
        craftCategory: "carpentry",
        sourceNodeId: "kim-bong-carpentry",
        sourceNodeName: "Làng Mộc Kim Bồng",
        artisanName: "Ông Nguyễn Văn Tiến",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
        rarity: "Rare",
        description: "Bản dập hoa văn rồng chầu nguyệt — motif kiến trúc đình làng thế kỷ 18.",
        descriptionEn: "Rubbing of a dragon-moon motif — 18th century communal house architectural pattern.",
        dropRate: 0.3,
      },
      {
        id: "kbcv-003",
        name: "Kèo cổ phục dựng",
        nameEn: "Restored Roof Truss Fragment",
        craftCategory: "carpentry",
        sourceNodeId: "kim-bong-carpentry",
        sourceNodeName: "Làng Mộc Kim Bồng",
        artisanName: "Ông Nguyễn Văn Tiến",
        image: "https://images.unsplash.com/photo-1581833971358-2c8b550f87b3?w=400&q=80",
        rarity: "Epic",
        description: "Mảnh kèo gỗ mít cổ phục dựng từ đình làng thế kỷ 17. Mỗi mẫu là duy nhất.",
        descriptionEn: "Restored jackwood roof truss fragment from a 17th century communal house. Each piece is unique.",
        dropRate: 0.08,
      },
      {
        id: "kbcv-004",
        name: "Bản vẽ đình làng",
        nameEn: "Village Communal House Blueprint",
        craftCategory: "carpentry",
        sourceNodeId: "kim-bong-carpentry",
        sourceNodeName: "Làng Mộc Kim Bồng",
        artisanName: "Ông Nguyễn Văn Tiến",
        image: "https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=400&q=80",
        rarity: "Common",
        description: "Bản phác thảo kiến trúc đình làng truyền thống theo tỉ lệ 1:50.",
        descriptionEn: "Traditional communal house architectural sketch at 1:50 scale.",
        dropRate: 0.5,
      },
      {
        id: "kbcv-005",
        name: "Mộc bản gia truyền",
        nameEn: "Heirloom Wood Block Print",
        craftCategory: "carpentry",
        sourceNodeId: "kim-bong-carpentry",
        sourceNodeName: "Làng Mộc Kim Bồng",
        artisanName: "Ông Nguyễn Văn Tiến",
        image: "https://images.unsplash.com/photo-1579762715118-a6f1d4b934f1?w=400&q=80",
        rarity: "Legendary",
        description: "Mộc bản gỗ thị khắc chữ Nôm — lưu giữ bài thơ ca ngợi làng nghề từ thế kỷ 19.",
        descriptionEn: "Persimmon wood block carved with Chu Nom script — preserving a 19th century poem praising the craft village.",
        dropRate: 0.02,
      },
    ],
  },
  {
    id: "thuy-xuan-incense",
    name: "Làng Hương Thủy Xuân",
    nameEn: "Thuy Xuan Incense Village",
    craftCategory: "incense",
    coordinates: [107.5634, 16.4420],
    coverImage: "https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800&q=80",
    tier: 1,
    artisanName: "Bà Nguyễn Thị Lan",
    artisanAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80",
    knowledgeSummary:
      "Làng hương Thủy Xuân nằm ở phía Tây thành phố Huế, nổi tiếng với nghề làm hương trầm thủ công. Hương được làm từ bột trầm hương, quế, hồi, và các loại thảo mộc tự nhiên, phơi khô tự nhiên dưới nắng Huế.",
    knowledgeSummaryEn:
      "Thuy Xuan incense village lies west of Hue city, renowned for handcrafted agarwood incense. Incense is made from agarwood powder, cinnamon, star anise, and natural herbs, air-dried under Hue's warm sun.",
    materials: ["Bột trầm hương", "Quế", "Hồi", "Hương bài"],
    videoUrl: undefined,
    npcScript: [
      {
        order: 1,
        question: "Hương trầm Thủy Xuân khác gì hương thường?",
        answer:
          "Hương của chúng tôi không có hóa chất — 100% nguyên liệu tự nhiên. Trầm hương thật có mùi trầm ấm sâu, không hắc. Khi đốt, khói nhẹ và uốn lượn — đó là dấu hiệu chất lượng.",
      },
      {
        order: 2,
        question: "Công thức pha bột hương có bí mật không?",
        answer:
          "Có chứ! Tỉ lệ pha bột trầm, quế, hồi là bí quyết gia truyền 3 đời. Mỗi gia đình Thủy Xuân có tỉ lệ riêng — vì vậy mỗi nhà hương lại có mùi khác nhau một chút. Tôi không tiết lộ được (cười).",
      },
      {
        order: 3,
        question: "Làm một que hương mất bao lâu?",
        answer:
          "Từ khi pha bột đến khi đóng gói mất 3 ngày. Ngày 1 pha bột và quết lên que; ngày 2 phơi nắng; ngày 3 đóng gói. Nếu trời mưa thì kéo dài 5–7 ngày. Hương Thủy Xuân không sấy — phải phơi tự nhiên.",
      },
    ],
    photoChallenge: {
      prompt: "Chụp ảnh giá phơi hương dưới nắng",
      promptEn: "Photograph the incense drying racks in the sun",
      referenceImages: [
        "https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&q=70",
        "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=70",
      ],
    },
    items: [
      {
        id: "txin-001",
        name: "Bó hương trầm",
        nameEn: "Agarwood Incense Bundle",
        craftCategory: "incense",
        sourceNodeId: "thuy-xuan-incense",
        sourceNodeName: "Làng Hương Thủy Xuân",
        artisanName: "Bà Nguyễn Thị Lan",
        image: "https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&q=80",
        rarity: "Common",
        description: "Bó hương trầm 40 que, phơi tự nhiên, mùi trầm ấm đặc trưng Huế.",
        descriptionEn: "Bundle of 40 agarwood incense sticks, air-dried, with characteristic warm Hue agarwood fragrance.",
        dropRate: 0.6,
      },
      {
        id: "txin-002",
        name: "Khuôn hương vòng",
        nameEn: "Spiral Incense Mold",
        craftCategory: "incense",
        sourceNodeId: "thuy-xuan-incense",
        sourceNodeName: "Làng Hương Thủy Xuân",
        artisanName: "Bà Nguyễn Thị Lan",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
        rarity: "Rare",
        description: "Khuôn gỗ hình xoắn ốc dùng tạo hương vòng — dụng cụ truyền thống hiếm gặp.",
        descriptionEn: "Spiral wooden mold used to shape coil incense — a rare traditional tool.",
        dropRate: 0.25,
      },
      {
        id: "txin-003",
        name: "Hộp hương hoàng cung",
        nameEn: "Imperial Palace Incense Box",
        craftCategory: "incense",
        sourceNodeId: "thuy-xuan-incense",
        sourceNodeName: "Làng Hương Thủy Xuân",
        artisanName: "Bà Nguyễn Thị Lan",
        image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&q=80",
        rarity: "Epic",
        description: "Hộp hương trầm đặc biệt theo công thức hoàng cung triều Nguyễn — nồng độ trầm cao nhất.",
        descriptionEn: "Special agarwood incense box following Nguyen dynasty imperial court recipe — highest agarwood concentration.",
        dropRate: 0.1,
      },
      {
        id: "txin-004",
        name: "Công thức gia truyền",
        nameEn: "Secret Family Formula",
        craftCategory: "incense",
        sourceNodeId: "thuy-xuan-incense",
        sourceNodeName: "Làng Hương Thủy Xuân",
        artisanName: "Bà Nguyễn Thị Lan",
        image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
        rarity: "Legendary",
        description: "Tờ giấy dó ghi công thức pha bột hương gia truyền 3 đời — được trao bởi chính tay Bà Lan.",
        descriptionEn: "Dó paper recording the 3-generation family incense powder formula — personally entrusted by Bà Lan.",
        dropRate: 0.02,
      },
      {
        id: "txin-005",
        name: "Cây hương cuối mùa",
        nameEn: "Last-Season Agarwood Sprig",
        craftCategory: "incense",
        sourceNodeId: "thuy-xuan-incense",
        sourceNodeName: "Làng Hương Thủy Xuân",
        artisanName: "Bà Nguyễn Thị Lan",
        image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&q=80",
        rarity: "Endangered",
        description: "Cành trầm hương tự nhiên cuối cùng từ rừng trầm Quảng Nam — loài cây đang cực kỳ nguy cấp.",
        descriptionEn: "Last natural agarwood sprig from Quang Nam agarwood forest — critically endangered species.",
        dropRate: 0.005,
      },
    ],
  },
  {
    id: "phu-bai-silk",
    name: "Làng Lụa Phú Bài",
    nameEn: "Phu Bai Silk Weaving Village",
    craftCategory: "silk",
    coordinates: [107.6847, 16.3583],
    coverImage: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=800&q=80",
    tier: 1,
    artisanName: "Bà Trần Thị Hoa",
    artisanAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&q=80",
    knowledgeSummary:
      "Làng lụa Phú Bài nổi tiếng với kỹ thuật dệt gấm triều Nguyễn — loại vải chỉ dành cho hoàng gia. Mỗi mét gấm cần 3–5 ngày dệt tay, với hoa văn rồng phượng được dệt nổi kỳ công.",
    knowledgeSummaryEn:
      "Phu Bai silk village is famous for Nguyen dynasty brocade weaving — fabric reserved exclusively for royalty. Each meter of brocade takes 3–5 days of hand-weaving, with raised dragon-phoenix patterns of extraordinary intricacy.",
    materials: ["Tơ tằm", "Thuốc nhuộm tự nhiên", "Khung dệt gỗ", "Chỉ vàng"],
    videoUrl: undefined,
    npcScript: [
      {
        order: 1,
        question: "Lụa Huế khác lụa Hà Đông thế nào?",
        answer:
          "Lụa Huế mỏng hơn, mịn hơn, và có hoa văn hoàng cung. Lụa Hà Đông thường màu trơn — lụa Huế có gấm nổi. Kỹ thuật dệt gấm của chúng tôi đòi hỏi 2 người cùng lúc — một người dệt, một người theo dõi hoa văn.",
      },
      {
        order: 2,
        question: "Học dệt lụa mất bao lâu?",
        answer:
          "3 năm học nghề cơ bản; 10 năm để dệt được hoa văn rồng phượng chuẩn. Tôi bắt đầu từ năm 16 tuổi — đến năm 26 mới dám nhận đơn gấm hoàng cung.",
      },
      {
        order: 3,
        question: "Màu sắc lụa từ đâu ra?",
        answer:
          "Truyền thống dùng thuốc nhuộm tự nhiên: đỏ từ cây lá điều, vàng từ nghệ và hoa hòe, xanh từ chàm. Hiện nay một số nghệ nhân dùng thuốc nhuộm công nghiệp — nhưng lụa gấm triều Nguyễn chính thống vẫn phải dùng màu tự nhiên.",
      },
    ],
    photoChallenge: {
      prompt: "Chụp ảnh khung dệt lụa truyền thống",
      promptEn: "Photograph the traditional silk weaving loom",
      referenceImages: [
        "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=400&q=70",
      ],
    },
    items: [
      {
        id: "pbsl-001",
        name: "Sợi tơ tằm thô",
        nameEn: "Raw Silk Thread Skein",
        craftCategory: "silk",
        sourceNodeId: "phu-bai-silk",
        sourceNodeName: "Làng Lụa Phú Bài",
        artisanName: "Bà Trần Thị Hoa",
        image: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=400&q=80",
        rarity: "Common",
        description: "Cuộn tơ tằm thô Phú Bài — nguyên liệu đầu vào của gấm hoàng cung.",
        descriptionEn: "Raw Phu Bai silk thread skein — the raw material for imperial brocade.",
        dropRate: 0.55,
      },
      {
        id: "pbsl-002",
        name: "Mẫu lụa phượng hoàng",
        nameEn: "Phoenix Silk Sample",
        craftCategory: "silk",
        sourceNodeId: "phu-bai-silk",
        sourceNodeName: "Làng Lụa Phú Bài",
        artisanName: "Bà Trần Thị Hoa",
        image: "https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=400&q=80",
        rarity: "Rare",
        description: "Mẫu vải lụa dệt hình phượng hoàng — motif dành cho hoàng hậu triều Nguyễn.",
        descriptionEn: "Silk fabric sample woven with phoenix motif — pattern reserved for Nguyen dynasty queens.",
        dropRate: 0.28,
      },
      {
        id: "pbsl-003",
        name: "Gấm rồng phượng hoàng cung",
        nameEn: "Imperial Dragon-Phoenix Brocade",
        craftCategory: "silk",
        sourceNodeId: "phu-bai-silk",
        sourceNodeName: "Làng Lụa Phú Bài",
        artisanName: "Bà Trần Thị Hoa",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
        rarity: "Epic",
        description: "Mảnh gấm rồng phượng hoàng cung dệt bằng chỉ vàng — chỉ 5 nghệ nhân Việt Nam còn biết kỹ thuật này.",
        descriptionEn: "Imperial dragon-phoenix brocade woven with gold thread — only 5 Vietnamese artisans still know this technique.",
        dropRate: 0.07,
      },
      {
        id: "pbsl-004",
        name: "Thẻ bài ký hiệu dệt",
        nameEn: "Weaving Pattern Card",
        craftCategory: "silk",
        sourceNodeId: "phu-bai-silk",
        sourceNodeName: "Làng Lụa Phú Bài",
        artisanName: "Bà Trần Thị Hoa",
        image: "https://images.unsplash.com/photo-1561715276-a2d087060f1d?w=400&q=80",
        rarity: "Rare",
        description: "Thẻ bài ghi ký hiệu dệt truyền thống — 'ngôn ngữ' của nghề dệt Phú Bài.",
        descriptionEn: "Card recording traditional weaving notations — the 'language' of Phu Bai weaving craft.",
        dropRate: 0.25,
      },
    ],
  },
  {
    id: "phuoc-tich-pottery",
    name: "Gốm Phước Tích",
    nameEn: "Phuoc Tich Pottery Village",
    craftCategory: "pottery",
    coordinates: [107.4574, 16.6028],
    coverImage: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&q=80",
    tier: 2,
    artisanName: "Ông Lê Trung Kiên",
    artisanAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80",
    knowledgeSummary:
      "Gốm Phước Tích là làng gốm hơn 500 năm tuổi bên dòng sông Ô Lâu, Thừa Thiên Huế. Sản phẩm gốm Phước Tích từng được chọn dùng trong hoàng cung nhà Nguyễn — đặc biệt là chum, lu, và đồ thờ cúng.",
    knowledgeSummaryEn:
      "Phuoc Tich pottery is a 500-year-old pottery village on the O Lau River in Thua Thien Hue. Phuoc Tich ceramics were once selected for use in the Nguyen dynasty royal court — especially jars, urns, and ritual objects.",
    materials: ["Đất sét Phước Tích", "Than củi", "Men tự nhiên", "Bàn xoay tay"],
    videoUrl: undefined,
    npcScript: [
      {
        order: 1,
        question: "Đất sét Phước Tích có gì đặc biệt?",
        answer:
          "Đất sét lấy từ bờ sông Ô Lâu — độ dẻo cao, ít tạp chất. Sau khi nung ở nhiệt độ 900°C, gốm Phước Tích có màu đỏ gạch đặc trưng và tiếng 'keng' trong như đồng khi gõ — đó là dấu hiệu chất lượng.",
      },
      {
        order: 2,
        question: "Kỹ thuật nung gốm truyền thống như thế nào?",
        answer:
          "Chúng tôi dùng lò nung đất truyền thống đốt bằng củi — không phải lò điện. Quy trình nung kéo dài 12–14 tiếng, kiểm soát nhiệt độ bằng kinh nghiệm của thợ. Lò điện cho ra màu đều đặn hơn, nhưng mất đi 'hồn' của gốm.",
      },
      {
        order: 3,
        question: "Tại sao gốm Phước Tích được dùng trong hoàng cung?",
        answer:
          "Vua Gia Long chọn gốm Phước Tích vì 3 lý do: bền, đẹp, và không nhiễm mùi. Lu gốm Phước Tích giữ nước trong mát ngay cả mùa hè Huế — không có mùi bùn hay đất. Hoàng tộc dùng để chứa nước uống và ngâm trái cây.",
      },
    ],
    photoChallenge: {
      prompt: "Chụp ảnh bàn xoay gốm đang hoạt động",
      promptEn: "Photograph a pottery wheel in use",
      referenceImages: [
        "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=400&q=70",
      ],
    },
    items: [
      {
        id: "ptpt-001",
        name: "Chén gốm Phước Tích",
        nameEn: "Phuoc Tich Ceramic Bowl",
        craftCategory: "pottery",
        sourceNodeId: "phuoc-tich-pottery",
        sourceNodeName: "Gốm Phước Tích",
        artisanName: "Ông Lê Trung Kiên",
        image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=400&q=80",
        rarity: "Common",
        description: "Chén ăn cơm gốm đỏ Phước Tích — sản phẩm căn bản của làng gốm 500 năm tuổi.",
        descriptionEn: "Red ceramic rice bowl from Phuoc Tich — the staple product of this 500-year-old pottery village.",
        dropRate: 0.55,
      },
      {
        id: "ptpt-002",
        name: "Khuôn đất nung cổ",
        nameEn: "Ancient Clay Mold",
        craftCategory: "pottery",
        sourceNodeId: "phuoc-tich-pottery",
        sourceNodeName: "Gốm Phước Tích",
        artisanName: "Ông Lê Trung Kiên",
        image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&q=80",
        rarity: "Rare",
        description: "Khuôn đất nung cổ thế kỷ 19 — dùng tạo hình đồ thờ cúng hoàng gia.",
        descriptionEn: "19th century antique clay mold — used to form royal ritual objects.",
        dropRate: 0.28,
      },
      {
        id: "ptpt-003",
        name: "Lu nước hoàng cung",
        nameEn: "Royal Water Urn",
        craftCategory: "pottery",
        sourceNodeId: "phuoc-tich-pottery",
        sourceNodeName: "Gốm Phước Tích",
        artisanName: "Ông Lê Trung Kiên",
        image: "https://images.unsplash.com/photo-1616627547584-bf28cee262db?w=400&q=80",
        rarity: "Epic",
        description: "Miniature lu nước theo mẫu hoàng cung — từng chứa nước uống cho vua Gia Long.",
        descriptionEn: "Miniature water urn following royal court design — once used to hold drinking water for King Gia Long.",
        dropRate: 0.09,
      },
      {
        id: "ptpt-004",
        name: "Mảnh gốm khảo cổ",
        nameEn: "Archaeological Pottery Shard",
        craftCategory: "pottery",
        sourceNodeId: "phuoc-tich-pottery",
        sourceNodeName: "Gốm Phước Tích",
        artisanName: "Ông Lê Trung Kiên",
        image: "https://images.unsplash.com/photo-1608889825205-eebdb9fc5806?w=400&q=80",
        rarity: "Legendary",
        description: "Mảnh gốm Phước Tích thế kỷ 16–17 được tìm thấy ở di chỉ khảo cổ làng — chứng nhân lịch sử thực sự.",
        descriptionEn: "16th–17th century Phuoc Tich pottery shard found at village archaeological site — a true historical witness.",
        dropRate: 0.015,
      },
    ],
  },
  {
    id: "phu-cam-conical-hat",
    name: "Làng Nón Phú Cam",
    nameEn: "Phu Cam Conical Hat Village",
    craftCategory: "hat-making",
    coordinates: [107.5677, 16.4453],
    coverImage: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=800&q=80",
    tier: 1,
    artisanName: "Bà Võ Thị Mai",
    artisanAvatar: "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=200&q=80",
    knowledgeSummary:
      "Làng nón Phú Cam nằm ngay trong thành phố Huế, nổi tiếng với nón bài thơ — loại nón đặc sản Huế có hình ảnh Thiên Mụ, cầu Trường Tiền được ép giữa hai lớp lá.",
    knowledgeSummaryEn:
      "Phu Cam conical hat village lies within Hue city, famous for 'bai tho' (poetry) hats — Hue's specialty hat with images of Thien Mu pagoda and Truong Tien bridge pressed between two layers of leaves.",
    materials: ["Lá cọ", "Tre chẻ nhỏ", "Chỉ khâu", "Hình ảnh ép"],
    videoUrl: undefined,
    npcScript: [
      {
        order: 1,
        question: "Nón bài thơ Huế khác nón thường thế nào?",
        answer:
          "Nón bài thơ đặc biệt vì giữa hai lớp lá có ép hình ảnh phong cảnh Huế và những câu thơ. Khi soi nón lên ánh sáng, bạn thấy cảnh Thiên Mụ, cầu Trường Tiền, hay thơ Nguyễn Du hiện ra như ảo ảnh. Đó là điều chỉ Huế mới có.",
      },
      {
        order: 2,
        question: "Làm một chiếc nón mất bao lâu?",
        answer:
          "Một chiếc nón bài thơ đẹp cần 1–2 ngày làm liên tục. Khâu lá vào vành tre phải đều tay — nếu không đều thì nón méo. Khó nhất là ép hình ảnh giữa hai lớp lá sao cho không nhăn và căn giữa đúng vị trí.",
      },
      {
        order: 3,
        question: "Vật liệu lá cọ lấy từ đâu?",
        answer:
          "Lá cọ lấy từ rừng Quảng Trị — loại lá non mới mở, còn trắng xanh. Phải hái đúng mùa, đúng tuổi lá. Về nhà phơi khô, ép phẳng, rồi mới khâu. Ngày nay khó tìm lá cọ đúng chuẩn — nhiều người chuyển sang lá nhân tạo nhưng không đẹp bằng.",
      },
    ],
    photoChallenge: {
      prompt: "Chụp ảnh nghệ nhân đang khâu nón",
      promptEn: "Photograph an artisan stitching a conical hat",
      referenceImages: [
        "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=400&q=70",
      ],
    },
    items: [
      {
        id: "pcch-001",
        name: "Nón bài thơ Thiên Mụ",
        nameEn: "Thien Mu Poetry Conical Hat",
        craftCategory: "hat-making",
        sourceNodeId: "phu-cam-conical-hat",
        sourceNodeName: "Làng Nón Phú Cam",
        artisanName: "Bà Võ Thị Mai",
        image: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=400&q=80",
        rarity: "Common",
        description: "Nón bài thơ ép hình chùa Thiên Mụ — biểu tượng du lịch Huế.",
        descriptionEn: "Poetry hat with Thien Mu pagoda image pressed inside — iconic symbol of Hue tourism.",
        dropRate: 0.6,
      },
      {
        id: "pcch-002",
        name: "Vành tre chẻ nón",
        nameEn: "Hat-Making Bamboo Frame",
        craftCategory: "hat-making",
        sourceNodeId: "phu-cam-conical-hat",
        sourceNodeName: "Làng Nón Phú Cam",
        artisanName: "Bà Võ Thị Mai",
        image: "https://images.unsplash.com/photo-1540979388789-6cee28a1cdc9?w=400&q=80",
        rarity: "Rare",
        description: "Bộ vành tre chẻ mỏng dùng làm khung nón — được uốn thủ công từng chiếc một.",
        descriptionEn: "Set of thinly split bamboo frames for hat-making — each one hand-bent individually.",
        dropRate: 0.3,
      },
      {
        id: "pcch-003",
        name: "Nón thơ Truyện Kiều",
        nameEn: "Tale of Kieu Poetry Hat",
        craftCategory: "hat-making",
        sourceNodeId: "phu-cam-conical-hat",
        sourceNodeName: "Làng Nón Phú Cam",
        artisanName: "Bà Võ Thị Mai",
        image: "https://images.unsplash.com/photo-1519817914152-22d216bb9170?w=400&q=80",
        rarity: "Legendary",
        description: "Nón bài thơ đặc biệt ép 8 câu Truyện Kiều thư pháp — chỉ làm theo đơn đặt hàng, cực kỳ hiếm.",
        descriptionEn: "Special poetry hat with 8 calligraphied lines from Tale of Kieu — made to order only, extremely rare.",
        dropRate: 0.03,
      },
    ],
  },
];

export const TOTAL_ITEMS = HERITAGE_NODES.reduce((sum, node) => sum + node.items.length, 0);
